CRM/Contract/Form/RapidCreate.php
js/rapidcreate_address_autocomplete.js
templates/CRM/Contract/Form/RapidCreate.tpl

* Add country/state fields.
* Add autocomplete for street, postcode, city, state (only if Country=Austria).
* PostcodeAT extension should be installed for this to work.

GP949: Use postcode.at extension also in rapid create form adress fields

---

CRM/Contract/Form/Create.php
CRM/Contract/Form/RapidCreate.php
CRM/Contract/FormUtils.php
CRM/Contract/RecurringContribution.php
CRM/Contract/SepaLogic.php
contract.php
templates/CRM/Contract/Form/Create.tpl
templates/CRM/Contract/Form/Modify.tpl
templates/CRM/Contract/Form/RapidCreate.tpl

Instead of using a hardcoded currency value, use the currency associated with the creditor or recurring contribution, depending on the view.
Fixes #17

GP-1791: Use Currency from SEPA Creditor and Recurring Contribution

---

CRM/Contract/Handler/ModificationConflicts.php

This throws an exception if a conflict check is initiated with an empty contract ID. Without this check, the contract extension will set 10,000 unrelated activities with an empty source_record_id to "Needs Review".

GP-1819: Fail if contract ID is empty in conflict check

---

CRM/Contract/SepaLogic.php

When a new mandate and recurring contribution is created, and if the activity campaign is empty, use the campaign of the previous recurring contribution instead of the membership campaign.

GP-1839: Use campaign from previous recurring contribution

---

CRM/Contract/FormUtils.php

This allows for easier customization of the download link in other extensions. See https://github.com/greenpeace-cee/at.greenpeace.uimods/commit/cc7b0de55cf9f17fb97d859684e88b0bf4ede231 for an example use-case.

GP-1916: Add name for contract download script

---

contract.php

Previously, the "delete in CiviMember" permission was used to allow or deny access to the core membership edit form. This introduces a new, dedicated permission for the edit form, making it possible to give users access to the edit feature while not allowing them to delete memberships.

GP-814: Add permission for core membership edit form

---

CRM/Contract/Handler/Contract.php
CRM/Contract/SepaLogic.php
CRM/Contract/Utils.php
api/v3/Contract.php
resources/custom_group_contract_updates.json
resources/custom_group_membership_payment.json

This adds a `defer_payment_start` field to `membership_payment`. If the field is set to `1` (default), new mandates created for existing memberships will respect already-paid membership periods and use a start date after the paid period. This was the previous behaviour.
If the value is set to `0`, contract modifications will not respect paid periods and use the current date for the mandate's start date.

GP-1790: Make start_date deferral for paid periods optional

---

CRM/Contract/Upgrader.php

This is a follow-up to #24 and adds an upgrader which defines the `defer_payment_start` custom fields.

GP-1790: Add Upgrader for defer_payment_start

---

CRM/Contract/Page/Review.php
templates/CRM/Contract/Page/Review.tpl

Instead of always showing the default currency, this fetches the currency from the currently active recurring contribution.

Show correct currency on contract review page

---

CRM/Contract/Form/Create.php
CRM/Contract/Form/Modify.php
CRM/Contract/Form/RapidCreate/AT.php
CRM/Contract/Form/RapidCreate/PL.php
CRM/Contract/FormUtils.php
CRM/Contract/Page/Review.php
contract.php
css/contract.css

- Remove use of `addWysiwyg()` when running under 4.7+
- Remove resource reference to `ckeditor.js` when running under 4.7+
- Hide "Renew-Credit Card" membership action
- Exclude contract review rows from shoreditch overflow handling
- Don't load contract custom field label when value is empty

Improve compatibility with CiviCRM 4.7+

---

CRM/Contract/Form/RapidCreate/AT.php
CRM/Contract/Form/RapidCreate/PL.php
CRM/Contract/Handler/Contract.php
CRM/Contract/SepaLogic.php

Amounts of >= 1000 are returned using thousands separator in some places. This causes issues when attempting to do math with these values, potentially leading to massive changes in annual amount e.g. when resuming pauses.

GP-2027: Apply formatMoney before doing any math

---

CRM/Contract/Upgrader.php

Update 1370 included a schema change, but did not call `fixSchemaDifferences()`.

GP-2075: Add logging schema fix to upgrader

---

CRM/Contract/ModificationActivity.php

`CRM_Contract_ModificationActivity::findByStatusChange` references `$this->startStatus` instead of `$startStatus`. That causes a warning on PHP 7.

Fix reference to $this in static method

---

templates/CRM/Member/Page/Tab.js

This fixes a JavaScript error that can be triggered by first opening the membership tab and then performing any other action on the contact that might involve a dialog being closed.

Fix a JavaScript error in dialogs after membership tab was opened

---

CRM/Contract/Handler/Contract.php

When memberships with file fields are updated, the contract handler tries to set the custom field to an array, while the API expects a file ID instead.
GP-2156

Fix handling of file fields

---

CRM/Contract/Change.php
CRM/Contract/Change/Cancel.php
CRM/Contract/Change/Resume.php
CRM/Contract/Handler/ModificationConflicts.php
CRM/Contract/Utils.php
api/v3/Contract/Modify.php
api/v3/Contract/ProcessScheduledModifications.php
tests/phpunit/CRM/Contract/BasicEngineTest.php
tests/phpunit/CRM/Contract/ContractTestBase.php
tests/phpunit/CRM/Contract/EngineStressTest.php

This fixes various issues in conflict and error handling:
- `CRM_Contract_Change::checkForConflicts()` was passing the activity ID of a modification to `CRM_Contract_Handler_ModificationConflicts`, which expected the contract ID instead.
- `CRM_Contract_Change::checkForConflicts()` was not called after a change was executed
- Exceptions encountered during execution of contract changes didn't cause the change activity to be set to status "Failed"
- Exceptions encountered prior to the execution of contract changes weren't reported back by `Contract.process_scheduled_modifications`
- Status changes were performed even if they didn't make sense (e.g. cancelling an already-cancelled membership) when processing contract changes
Includes unit tests for these issues.

Fix conflict and error handling

---

CRM/Contract/Form/Create.php
CRM/Contract/Form/Modify.php
CRM/Contract/Form/RapidCreate/AT.php
CRM/Contract/Form/RapidCreate/PL.php

This adds the `submitOnce` attribute to all form buttons to prevent accidental double-submission.

GP-6589 Add submitOnce attribute for all form buttons

---

.circleci/config.yml

This changes our text matrix in CI:
- Drop Civi 5.7 and Civi 5.13 - tests started failing due to PHP being upgraded in the docker image
- Add Civi 5.21 (old ESR), Civi 5.24 and Civi 5.27 (ESR)
- Switch from MariaDB 10.2 and 10.3 to 10.3 and 10.4
Tests now run against master, stable, 5.27, 5.24 and 5.21.

Update dependencies in CI config

---

Civi/Contract/ActionProvider/Action/CancelContract.php
Civi/Contract/ActionProvider/Action/CreateContract.php
Civi/Contract/ActionProvider/Action/GetContract.php
Civi/Contract/ActionProvider/Action/GetSepaRcur.php
Civi/Contract/ActionProvider/Action/PauseContract.php
Civi/Contract/ActionProvider/Action/ResumeContract.php
Civi/Contract/ActionProvider/Action/ReviveContract.php
Civi/Contract/ActionProvider/Action/UpdateContract.php
Civi/Contract/ContainerSpecs.php
contract.php
info.xml

To be able to use the Contract Extension in Custom APIs these Formprocessor Actions are very usefull.

Add Formprocessor Actions to Contract Extension

---

CRM/Contract/Form/Create.php

This validates that `join_date` is <= today in order to prevent membership status calculation errors.

GP-8315 Add form validation to ensure join_date is <= today on membership form

---

Civi/Contract/ActionProvider/Action/GetSepaRcur.php

The FormProcessorAction GetSepaRcur Request did use the wrong parameter.

Bugfix: FormProcessorAction GetSepaRcur Request parameter fixed

---

Civi/Contract/Event/RenderChangeSubjectEvent.php
tests/phpunit/CRM/Contract/BugFollowupTest.php
tests/phpunit/CRM/Contract/CompatibilityTest.php
tests/phpunit/CRM/Contract/ContractTestBase.php

Fixes garbled amount texts in records (activities) for large amounts.

[#79] fixed activity title issues with changes including thousand separator

---

templates/CRM/Member/Page/Tab.js

When loading details for a contract in the membership list on a contact, the browser's print dialog opens. This is due to the `snippet=1` query parameter, which tells CiviCRM to include the `print.tpl` template invoking `window.print()`
The correct Ajax snippet is `2` for not including CMS/CiviCRM assets for embedding Ajax-loaded content, see https://github.com/civicrm/civicrm-core/blob/f0a6e00f9aa30906848a23129fec1f46b4d2739b/CRM/Core/Smarty.php#L29-L46
*systopia-reference: 29190*

Use Ajax snippet 2 for not printing when loading contract details in membership table

---

CRM/Contract/Form/Create.php

*systopia-reference: 29575*
This would have stored the mandate ID instead of the recurring contribution ID and thus caused issues when attempting to update/end the membership.

Correctly record recurring contribution ID for new contracts with SEPA mandate

---

api/v3/Contract/Create.php

*systopia-reference: 30088*
This adds a parameter `activity_date_time` to the `Contract.create` APIv3 which is being passed to `Activity.create` so that e.g. for imports the activity date can be set to something else than the date/time of execution.

Allow passing activity's date/time in `Contract.create` API

---

CRM/Contract/Upgrader.php
tests/phpunit/CRM/Contract/Form/CreateFormTest.php
tests/phpunit/CRM/Contract/Form/ModifyFormTest.php

- Replace hardcode ids with dynamic lookups via getPaymentInstrumentIdByName for RCUR/Cash/None.
- Flush PseudoConstant cache and retry when the option may have been freshly created.
- Do not force payment_instrument_id on the "existing" path.
- Prevent "'X' is not a valid option for field payment_instrument_id" and make tests portable across DBs (local/Docker/CI)

test(ModifyForm): resolve payment_instrument_id by name

---

CRM/Contract/BAO/ContractPaymentLink.php
CRM/Contract/FormUtils.php

Replaces deprecated function name with the forward-compat equivalent.
Note: the new getTemplateVars function has been available since CiviCRM 5.70.

Update call to deprecated Smarty::get_template_vars
